name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Update to the recommended version

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Can be simplified if there are no tests implemented

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: npm run deploy  # Command for the deploy
